# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_adress',
            new_name='customer_adressa',
        ),
    ]
