# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170815_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_adressa',
            new_name='customer_address',
        ),
    ]
