# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170815_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='prise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
