# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170815_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
