# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170815_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='quantity',
        ),
    ]
