# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_productinorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
