# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_productinorder_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_prise',
            new_name='total_price',
        ),
    ]
