# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_productincard_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincard',
            name='order',
        ),
    ]
