# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_productincard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincard',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='productincard',
            name='qty',
            field=models.IntegerField(default=None),
        ),
    ]
