# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20170903_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincard',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
