# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20170903_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincard',
            old_name='price_per_item',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productincard',
            old_name='nmb',
            new_name='qty',
        ),
    ]
