# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20170923_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custormer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
