# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
    ]
