# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170819_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
