# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
