# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170820_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/static/media/product_img'),
        ),
    ]
