# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170821_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='store/static/media/product_img/12.jpg', upload_to='store/static/media/product_img'),
        ),
    ]
