# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170822_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_img'),
        ),
    ]
