# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170823_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
